### ISSUE TITLE
关于提供的两个预训练权重

### ISSUE THREAD

**Issue by vae1118** [softwarePupil/ImgProcess#1]
关于在百度网盘中提供的预训练权重：

请问`centernet_resnet50_voc.pth`这个权重是在怎样的模型上训练之后得到的，可以在本次的项目的模型中正常运行吗？

我使用这个权重并运行`predict.py`以及`get_map.py`文件时会报**维度不匹配**的错：

![issue](https://github.com/softwarePupil/ImgProcess/assets/120458362/b6ed2b6f-4ec4-477b-be1f-752a3761ffcf)

猜测这个权重应该是在类别数为20的模型上训练得到的，而测试时在`model_data\classes.txt`文件中只指定了`person`这1个类别？

感谢答疑！我的环境是`Pytorch 2.0.1+cu117`，`python 3.10.12`。

**Comment by softwarePupil** [comment]
您好，预训练权重分为两个，分别是`centernet_resnet50_voc.pth`和`centernet_resnet50_voc.pth`。他们分别在VOC数据集和数图作业数据集中训练得到。由于VOC数据集是20分类的，于是出现了上面问题中错误，这点与您的猜想是一致的。我们的检测任务是单一分类检测问题，所以`centernet_resnet50_voc.pth`并不能直接胜任。
对于`centernet_resnet50_50.pth`来说，是利用数图作业的数据集得到的。它可以直接完成数图检测任务的，正因为他是单分类任务。不过随机的参数设置可能限制了它的性能上限。
我原本的想法是，同学们可以利用`centernet_resnet50_voc.pth`作为优秀的模型起点，从头训练。

**Comment by vae1118** [comment]
@softwarePupil 好的，我明白了。感谢回复！
