### ISSUE TITLE
数据集解压缩问题

### ISSUE THREAD

**Issue by reveyd** [softwarePupil/ImgProcess#3]
请问下载出来的数据集压缩包的后缀.aa和.ab是要删去后解压缩.zip文件吗，还是要怎样打开这两个文件呢，我在删去之后用winrar进行解压缩，提示数据已经损坏，无法解压缩，用7z解压缩过程中也是显示很多文件的数据不可用，解压缩完成之后Annotations和ImagesSets文件夹中也是空的，只有图片文件，这要怎样解决呢，还是整个过程是不能在windows系统下进行解压缩的》

**Comment by softwarePupil** [comment]
您好，如果你想在Windows中进行解压，需要将.aa和.ab改为.001和.002，之后使用解压软件如winRAR、Bandizip解压，如果有什么意外的问题，欢迎与我联系

**Comment by reveyd** [comment]
@softwarePupil 好的好的，感谢！
