### ISSUE TITLE
显存不足错误

### ISSUE THREAD

**Issue by cfydm** [softwarePupil/ImgProcess#5]
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
![image](https://github.com/softwarePupil/ImgProcess/assets/101536224/254de3da-d3d3-4c57-b460-f64978e36858)
出现了以上报错，使用的设备显卡是6GB显存的3060laptop，设置的参数如下：
    Init_Epoch          = 0
    Freeze_Epoch        = 1
    Freeze_batch_size   = 2
   
    UnFreeze_Epoch      = 1
    Unfreeze_batch_size = 2
请问是参数设置得有错误还是因为显存的确不够，应该如何解决呢

**Comment by softwarePupil** [comment]
这种情况下建议调小图像的输入尺寸，但是带来的损失是精度会有一定下降，这里推荐一种较为麻烦的方法可以保证精度且降低显存占用：“对数据进行预处理，将数据切分成更小的图像，但这样会有些麻烦，因为切分后要进行拼接“，不过我不清楚你的显卡是怎样的，我记得我在做预训练权重的时候只用了5kM，你可以看一下”nvidia-smi“是否有其他占用显存的进程

**Comment by cfydm** [comment]
我将输入尺寸设置成32*32之后，可以进行训练，进度条会增长，但是大约在进度条走到5%到10%时会出现如下报错：_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError
试了几次都是这样，并且在尝试多次以后还出现了pycharm闪退和电脑分辨率异常情况（怀疑是显卡驱动崩溃，因为和没安显卡驱动的电脑分辨率看起来比较像），请问这个错误是由什么引起的以及如何解决

**Comment by softwarePupil** [comment]
如果您将输入尺寸改成32*32才能运行的话，并且在运行的时候电脑出现闪退等问题，那我建议您换成另一个作业任务，或者直接用我事先的预训练进行微调，并且建议推理的时候只是用CPU，不过感觉您的电脑是不是显存和内存在运行程序的时候占用的太多了

**Comment by Ustinianing** [comment]
同6GB显存的3060也一样的报错，改成cpu后可以跑
