### ISSUE TITLE
map值问题

### ISSUE THREAD

**Issue by reveyd** [softwarePupil/ImgProcess#6]
您好，我在训练过程中输出的收敛后的验证集map值，与单独运行get_map.py输出的验证集的map值相差较大，大概相差15个百分点左右，请问这是什么原因呢？

**Comment by softwarePupil** [comment]
您好，您能否讲你的书出结果展示给我呢？
我有以下几种猜测：
1.两个地方的IOU或者置信度阈值设置不同？
2.一个地方使用VOC测试方案，另一个地方使用Coco测试方案？
3.否是同一个模型权重推理的输出结果？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月18日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [softwarePupil/ImgProcess] map值问题 (Issue #6) |

您好，我在训练过程中输出的收敛后的验证集map值，与单独运行get_map.py输出的验证集的map值相差较大，大概相差15个百分点左右，请问这是什么原因呢？
