### ISSUE TITLE
数据集能不能给个阿里云盘的链接

### ISSUE THREAD

**Issue by Ustinianing** [softwarePupil/ImgProcess#7]
百度云一直下不来，云盘2个文件一起解压报错
<img width="308" alt="Snipaste_2023-12-19_15-07-01" src="https://github.com/softwarePupil/ImgProcess/assets/44403417/42ee9820-7e57-47e4-a2af-7abb50e169a7">

**Comment by softwarePupil** [comment]
请问您是用windows解压的么，解压的时候改后缀了么

**Comment by Ustinianing** [comment]
> 请问您是用windows解压的么，解压的时候改后缀了么

win11，分别改成01，02了用的7z解压的，以前解压游戏也没出过问题

**Comment by softwarePupil** [comment]
![image](https://github.com/softwarePupil/ImgProcess/assets/75232711/58891254-1bae-4912-8d93-7824ccd385ea)
如果还不行
联系助教，线下拷给你
